version: '3.8'
##
services:
  api:
    environment:
    - AGRSERVICECORE_ConnectionStrings__AGRConnectionString=Data Source=${SQL_SERVER};Initial Catalog=${PROD_DB};User=${SQL_USER};Password=${SQL_PASS}
    - AGRSERVICECORE_ConnectionStrings__STGConnectionString=Data Source=${SQL_SERVER};Initial Catalog=${STG_DB};User=${SQL_USER};Password=${SQL_PASS}
    image: "agrinventory/api:local"
    ports:
      - "6000:5000"
    build: 
      context: ../agr-services
      dockerfile: Api/Dockerfile
  databases:
    image: "db:local"
    ports:
      - "5100:5000" #localhost:5100
    environment:
      - SQL_SERVER=sqlserver
      - SQL_USER=sa
      - SQL_PASS=Strong!Password9
      - PROD_PROJ_NAME=dev_inventory_prod
      - PROD_DEPLOY_DB_NAME=${PROD_DB}
      - PROD_PUBLISH_PARAMS=/v:BD_DEV_ERP_DB=${ERP_DB}
        /v:BD_DEV_PROD_DB=${PROD_DB} /v:BD_DEV_STG_DB=${STG_DB}
        /v:BD_DEV_PARAMETERS=dummy=1 /v:BD_DEV_DBS=nav /v:BD_DEV_MODULES=none
        /v:BD_DEV_VERSION=6.3.0
      - STG_PROJ_NAME=dev_inventory_stg_nav2009
      - STG_DEPLOY_DB_NAME=${STG_DB}
      - STG_PUBLISH_PARAMS=/v:AGR_PROD_DB_NAME=${PROD_DB}
        /v:AGR_STG_DB_NAME=${STG_DB} /v:ERP_DB_NAME=${ERP_DB}
        /v:BD_DEV_ERP_DB=${ERP_DB} /v:BD_DEV_PROD_DB=${PROD_DB}
        /v:BD_DEV_STG_DB=${STG_DB} /v:BD_DEV_PARAMETERS=dummy=1
        /v:BD_DEV_DBS=nav /v:BD_DEV_MODULES=none /v:BD_DEV_VERSION=6.3.0
      - ERP_PROJ_NAME=erp-database
      - ERP_DEPLOY_DB_NAME=${ERP_DB}
      - ERP_PUBLISH_PARAMS=/v:BD_DEV_PARAMETERS=dummy=1 /v:BD_DEV_DBS=nav
        /v:BD_DEV_MODULES=none /v:BD_DEV_VERSION=6.3.0
      - PUBLISH_ON_START=true
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    user: root
    environment:
      SA_PASSWORD: Strong!Password9
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
volumes:
  sqlserver-data: null
